// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.2
// source: collect.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cpuinfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//用户空间占用CPU百分比
	Us string `protobuf:"bytes,1,opt,name=us,proto3" json:"us,omitempty"`
	//内核空间占用cpu
	Sy string `protobuf:"bytes,2,opt,name=sy,proto3" json:"sy,omitempty"`
	Io string `protobuf:"bytes,3,opt,name=io,proto3" json:"io,omitempty"`
}

func (x *Cpuinfo) Reset() {
	*x = Cpuinfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collect_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cpuinfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cpuinfo) ProtoMessage() {}

func (x *Cpuinfo) ProtoReflect() protoreflect.Message {
	mi := &file_collect_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cpuinfo.ProtoReflect.Descriptor instead.
func (*Cpuinfo) Descriptor() ([]byte, []int) {
	return file_collect_proto_rawDescGZIP(), []int{0}
}

func (x *Cpuinfo) GetUs() string {
	if x != nil {
		return x.Us
	}
	return ""
}

func (x *Cpuinfo) GetSy() string {
	if x != nil {
		return x.Sy
	}
	return ""
}

func (x *Cpuinfo) GetIo() string {
	if x != nil {
		return x.Io
	}
	return ""
}

type Memoryinfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//物理内存
	Memused string `protobuf:"bytes,1,opt,name=memused,proto3" json:"memused,omitempty"`
	//虚拟内存
	Swapused string `protobuf:"bytes,2,opt,name=swapused,proto3" json:"swapused,omitempty"`
}

func (x *Memoryinfo) Reset() {
	*x = Memoryinfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collect_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Memoryinfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memoryinfo) ProtoMessage() {}

func (x *Memoryinfo) ProtoReflect() protoreflect.Message {
	mi := &file_collect_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memoryinfo.ProtoReflect.Descriptor instead.
func (*Memoryinfo) Descriptor() ([]byte, []int) {
	return file_collect_proto_rawDescGZIP(), []int{1}
}

func (x *Memoryinfo) GetMemused() string {
	if x != nil {
		return x.Memused
	}
	return ""
}

func (x *Memoryinfo) GetSwapused() string {
	if x != nil {
		return x.Swapused
	}
	return ""
}

type Process struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid     string `protobuf:"bytes,5,opt,name=pid,proto3" json:"pid,omitempty"`
	User    string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Mem     string `protobuf:"bytes,3,opt,name=mem,proto3" json:"mem,omitempty"`
	Cpu     string `protobuf:"bytes,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
}

func (x *Process) Reset() {
	*x = Process{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collect_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_collect_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_collect_proto_rawDescGZIP(), []int{2}
}

func (x *Process) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *Process) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Process) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Process) GetMem() string {
	if x != nil {
		return x.Mem
	}
	return ""
}

func (x *Process) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

type Processinfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Processinfo []*Process `protobuf:"bytes,1,rep,name=processinfo,proto3" json:"processinfo,omitempty"`
}

func (x *Processinfo) Reset() {
	*x = Processinfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collect_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Processinfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Processinfo) ProtoMessage() {}

func (x *Processinfo) ProtoReflect() protoreflect.Message {
	mi := &file_collect_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Processinfo.ProtoReflect.Descriptor instead.
func (*Processinfo) Descriptor() ([]byte, []int) {
	return file_collect_proto_rawDescGZIP(), []int{3}
}

func (x *Processinfo) GetProcessinfo() []*Process {
	if x != nil {
		return x.Processinfo
	}
	return nil
}

type Diskinfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiskUser int32 `protobuf:"varint,1,opt,name=diskUser,proto3" json:"diskUser,omitempty"`
}

func (x *Diskinfo) Reset() {
	*x = Diskinfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collect_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Diskinfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diskinfo) ProtoMessage() {}

func (x *Diskinfo) ProtoReflect() protoreflect.Message {
	mi := &file_collect_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diskinfo.ProtoReflect.Descriptor instead.
func (*Diskinfo) Descriptor() ([]byte, []int) {
	return file_collect_proto_rawDescGZIP(), []int{4}
}

func (x *Diskinfo) GetDiskUser() int32 {
	if x != nil {
		return x.DiskUser
	}
	return 0
}

//收集消息汇总
type CollectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu     *Cpuinfo     `protobuf:"bytes,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Disk    *Diskinfo    `protobuf:"bytes,1,opt,name=disk,proto3" json:"disk,omitempty"`
	Proinfo *Processinfo `protobuf:"bytes,2,opt,name=proinfo,proto3" json:"proinfo,omitempty"`
	Meminfo *Memoryinfo  `protobuf:"bytes,3,opt,name=meminfo,proto3" json:"meminfo,omitempty"`
}

func (x *CollectInfo) Reset() {
	*x = CollectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collect_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectInfo) ProtoMessage() {}

func (x *CollectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_collect_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectInfo.ProtoReflect.Descriptor instead.
func (*CollectInfo) Descriptor() ([]byte, []int) {
	return file_collect_proto_rawDescGZIP(), []int{5}
}

func (x *CollectInfo) GetCpu() *Cpuinfo {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *CollectInfo) GetDisk() *Diskinfo {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *CollectInfo) GetProinfo() *Processinfo {
	if x != nil {
		return x.Proinfo
	}
	return nil
}

func (x *CollectInfo) GetMeminfo() *Memoryinfo {
	if x != nil {
		return x.Meminfo
	}
	return nil
}

//服务器硬件信息
type Computerinfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpuCount  string `protobuf:"bytes,1,opt,name=cpuCount,proto3" json:"cpuCount,omitempty"`
	CpuCore   string `protobuf:"bytes,2,opt,name=cpuCore,proto3" json:"cpuCore,omitempty"`
	MemCount  string `protobuf:"bytes,3,opt,name=memCount,proto3" json:"memCount,omitempty"`
	DiskCount string `protobuf:"bytes,4,opt,name=diskCount,proto3" json:"diskCount,omitempty"`
	MainBoard string `protobuf:"bytes,5,opt,name=mainBoard,proto3" json:"mainBoard,omitempty"`
}

func (x *Computerinfo) Reset() {
	*x = Computerinfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collect_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Computerinfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Computerinfo) ProtoMessage() {}

func (x *Computerinfo) ProtoReflect() protoreflect.Message {
	mi := &file_collect_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Computerinfo.ProtoReflect.Descriptor instead.
func (*Computerinfo) Descriptor() ([]byte, []int) {
	return file_collect_proto_rawDescGZIP(), []int{6}
}

func (x *Computerinfo) GetCpuCount() string {
	if x != nil {
		return x.CpuCount
	}
	return ""
}

func (x *Computerinfo) GetCpuCore() string {
	if x != nil {
		return x.CpuCore
	}
	return ""
}

func (x *Computerinfo) GetMemCount() string {
	if x != nil {
		return x.MemCount
	}
	return ""
}

func (x *Computerinfo) GetDiskCount() string {
	if x != nil {
		return x.DiskCount
	}
	return ""
}

func (x *Computerinfo) GetMainBoard() string {
	if x != nil {
		return x.MainBoard
	}
	return ""
}

var File_collect_proto protoreflect.FileDescriptor

var file_collect_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x39, 0x0a, 0x07, 0x63, 0x70, 0x75, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x73, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x6f, 0x22, 0x42, 0x0a, 0x0a, 0x6d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x75,
	0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x75, 0x73,
	0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x77, 0x61, 0x70, 0x75, 0x73, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x77, 0x61, 0x70, 0x75, 0x73, 0x65, 0x64, 0x22, 0x6d,
	0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x65, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x70, 0x75, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x70, 0x75, 0x22, 0x39, 0x0a,
	0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x0b,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x0b, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x26, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x6b,
	0x69, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x6b, 0x55, 0x73, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x69, 0x73, 0x6b, 0x55, 0x73, 0x65, 0x72,
	0x22, 0x97, 0x01, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1a, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x63, 0x70, 0x75, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x1d, 0x0a, 0x04,
	0x64, 0x69, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x64, 0x69, 0x73,
	0x6b, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x69, 0x73, 0x6b, 0x12, 0x26, 0x0a, 0x07, 0x70,
	0x72, 0x6f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x69,
	0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x69, 0x6e, 0x66,
	0x6f, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x9c, 0x01, 0x0a, 0x0c, 0x43,
	0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x70, 0x75, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x70, 0x75, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x70, 0x75, 0x43, 0x6f,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x70, 0x75, 0x43, 0x6f, 0x72,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x64, 0x69, 0x73, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x64, 0x69, 0x73, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d,
	0x61, 0x69, 0x6e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6d, 0x61, 0x69, 0x6e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_collect_proto_rawDescOnce sync.Once
	file_collect_proto_rawDescData = file_collect_proto_rawDesc
)

func file_collect_proto_rawDescGZIP() []byte {
	file_collect_proto_rawDescOnce.Do(func() {
		file_collect_proto_rawDescData = protoimpl.X.CompressGZIP(file_collect_proto_rawDescData)
	})
	return file_collect_proto_rawDescData
}

var file_collect_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_collect_proto_goTypes = []interface{}{
	(*Cpuinfo)(nil),      // 0: cpuinfo
	(*Memoryinfo)(nil),   // 1: memoryinfo
	(*Process)(nil),      // 2: process
	(*Processinfo)(nil),  // 3: processinfo
	(*Diskinfo)(nil),     // 4: diskinfo
	(*CollectInfo)(nil),  // 5: collectInfo
	(*Computerinfo)(nil), // 6: Computerinfo
}
var file_collect_proto_depIdxs = []int32{
	2, // 0: processinfo.processinfo:type_name -> process
	0, // 1: collectInfo.cpu:type_name -> cpuinfo
	4, // 2: collectInfo.disk:type_name -> diskinfo
	3, // 3: collectInfo.proinfo:type_name -> processinfo
	1, // 4: collectInfo.meminfo:type_name -> memoryinfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_collect_proto_init() }
func file_collect_proto_init() {
	if File_collect_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_collect_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cpuinfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collect_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Memoryinfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collect_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Process); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collect_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Processinfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collect_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Diskinfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collect_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collect_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Computerinfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_collect_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_collect_proto_goTypes,
		DependencyIndexes: file_collect_proto_depIdxs,
		MessageInfos:      file_collect_proto_msgTypes,
	}.Build()
	File_collect_proto = out.File
	file_collect_proto_rawDesc = nil
	file_collect_proto_goTypes = nil
	file_collect_proto_depIdxs = nil
}
